### ISSUE TITLE
Chips with global variables can't be saved as dupes

### ISSUE THREAD

**Issue by Fasteroid** [Vurv78/wire#11]
This includes entries in `@inputs`, `@outputs`, and `@persist`.  It triggers this "cyclic reference" error when you try to save a dupe containing the chip:
```
gamemodes/sandbox/entities/weapons/gmod_tool/stools/duplicator/transport.lua:30: attempt to serialize structure with cyclic reference
  1. TableToJSON - [C]:-1
   2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/stools/duplicator/transport.lua:30
    3. unknown - lua/includes/modules/concommand.lua:54
```

While a feature for protecting dupes from theft is honestly spectacular (and a directive for this should DEFINITELY be considered), the fact it triggers merely from using global variables is way too broken to be practical.

**Comment by Fasteroid** [comment]
The problem is located within `Entity.globvars` and `Entity.globvars_mut`:
![image](https://github.com/Vurv78/wire/assets/29342750/513d07c8-d708-4d3c-87d4-fb708d24af9a)
![image](https://github.com/Vurv78/wire/assets/29342750/23c123d0-8613-407f-8f46-44fcb2e143b6)

**Comment by Vurv78** [comment]
Should be fixed by https://github.com/Vurv78/wire/commit/f0aa7c664a684c61608a33715ea76a80fa5ee58f
