### ISSUE TITLE
unpersisted entity from if( first() ) is nil inside event

### ISSUE THREAD

**Issue by Fasteroid** [Vurv78/wire#4]
Entities defined inside a conditional but not @persist are nil if the current execution results in them not being defined.
This applies to events in particular.

[expression2-public/compiler_tests/entity-@persist-fakeout.txt](https://github.com/Fasteroid/expression2-public/blob/master/compiler_tests/entity-%40persist-fakeout.txt)
```golo
@name compiler_tests/entity-@persist-fakeout

#
# Bug Description:
#   Defining entity variables in if( first() ) and referencing them in
#   events results in nil values being retrieved.
#
# Current commit:
#   https://github.com/Vurv78/wire/commit/40ebf0653652b1723efbe575d165f5e6f2af45f4
#
# Relevant issue:
#   https://github.com/Vurv78/wire/issues/4
#

if( first() ){
    Entity = noentity()
}

event tick(){
    entity():weld(Entity)
}
```

**Comment by Vurv78** [comment]
Same behavior as current compiler
