### ISSUE TITLE
new compiler lacks handling for the "udf undefined at runtime" error

### ISSUE THREAD

**Issue by Fasteroid** [Vurv78/wire#6]
On the old compiler, the following is handled with a descriptive "UDF undefined at runtime":

[expression2-public/compiler_tests/function-undefined-at-runtime.txt](https://github.com/Fasteroid/expression2-public/blob/master/compiler_tests/function-undefined-at-runtime.txt)

```golo
@name compiler_tests/function-undefined-at-runtime

#
# Bug Description:
#   The original error thrown for calling a nonexistent UDF no longer exists
#   in the new compiler.
#
# Current commit:
#   https://github.com/Vurv78/wire/commit/40ebf0653652b1723efbe575d165f5e6f2af45f4
#
# Relevant issue:
#   https://github.com/Vurv78/wire/issues/6
#

if(0){
    function f(){}
}
f()
```

On the new compiler, this throws a generic internal error instead that might be hard for the average e2 user to figure out:
```
addons/wire/lua/entities/gmod_wire_expression2/base/compiler.lua:1430: attempt to call a nil value
```

**Comment by Vurv78** [comment]
Fixed by https://github.com/Vurv78/wire/commit/f330fc7c0ea43ccc4a1da7784f7bf0f4594c28a5
